# -*- coding: utf-8 -*-
"""Laboratorium2.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1lFP6tqQ3gWDew0tt9_kh7t3wlD6z0YwE

# Laboratorium 2

## Przypomnienie
"""

-493092, -313, 1, 19209, 3294052823049210391203910293003481039      # liczba całkowita
-393923.8132132, -1.0000001, 9031023901248120.2103912               # liczba zmiennoprzecinkowa
'kotek ma płotek', "kota", 'lubię pisać programy w Pythonie'        # Łańcuchy znakowe
True, False                                                         # Wartości logiczne

"""### Zmienna
Zmienną nazwany obszar w pamięci komputera pod którym można przechowywać dane. Innaczej można sobie wyobrazić ją jako podpisane (na początku puste) pudełko do którego wsadzamy określone rzeczy. 

Nazwa zmiennej jest dowolna, jednak sugerowane jest nazywanie jest zgodnie z przeznaczeniem lub informacją którą ma przechowywać.

przykłady:

"""

imie = 'Michał'             # zmienna przechowująca łańcuch znakowy Michał
liczba_calkowita = 5        # zmienna przechowująca wartość liczbową 5
liczba_rzeczywista = 3.44   # zmienna przechowująca liczbę rzeczywistą 3.44
prawda = True               # zmienna przechowująca wartość logiczną (True / False)
type(imie), type(liczba_calkowita), type(liczba_rzeczywista), type(prawda)

"""Język Python jest dynamicznym językiem programowania, typ zmiennej jest określany w trakcie przypisania na podstawie wartości."""

zmienna1 = 'Paweł'    # jest to teraz zmienna typu str (String - Łańcuch znakowy)
print(f'zmienna1={zmienna1}, typ={type(zmienna1)}')
zmienna1 = 12345      # teraz typ zostanie określony na int (Integer - liczba całkowita)
print(f'zmienna1={zmienna1}, typ={type(zmienna1)}')
zmienna1 = 0.4533113  # nowy typ na podstawie przypisania wartości do zmiennej będzie: float (liczba zmienno przecinkowa)
print(f'zmienna1={zmienna1}, typ={type(zmienna1)}')

"""### Operacje artmetyczne

przykłady:
"""

# Dodawanie
5 + 10

# Odejmowanie
4 - 8

# mnożenie
7 * 19

# Potęgowanie
3 ** 4

# Dzielenie
8 / 9

# Dzielenie całkowite
8 // 9   # to samo co: int(8 / 9)

# Reszta z dzielenia (znak modulo)
9 % 4

"""### Operacje na łańcucach znakowych

przykłady:
"""

# łączenie łańcuchów znakowych
'kot' + ' lubi mleko'

# łączenie łańcuchów znakowych z przypisaniem do nowej zmiennej
tekst = 'kot' + ' lubi mleko'
print(tekst)

# łączenie dwóch zmiennych typu str (string) z wykorzystaniem znaku +
kot = 'Kot'
lubi = 'lubi mleko'
tekst = kot + ' ' + lubi  # ' ' znak spacji dodany po środku, w innym przypadku otrzymalibyśmy 'Kotlubi mleko'
print(tekst)

# powielanie łańcuchów znakowych
'$' * 10

# Długość łańcucha znakowego
len('ala ma kota')

tekst = 'ala ma kota'
len(tekst)

# porównanie , operator ==
tekst1 = 'ala ma kota'
tekst2 = 'ala ma psa'
tekst1 == tekst2

# porównanie , operator ==
tekst1 = 'ala ma kota'
tekst2 = 'ala ma kota'
tekst1 == tekst2

"""Formatowanie tekstu:"""

# z wykorzystaniem f-string
imie = 'Ala'
co = 'Kota'
wiadomosc = f'{imie} ma {co}'
wiadomosc

# z wykorzystaniem  str.format() (https://docs.python.org/3/library/stdtypes.html#str.format)
imie = 'Ala'
co = 'Kota'
wiadomosc = '{} ma {}'.format(imie, co)  # kolejność ma znaczenie
wiadomosc

# Stary sposób formatowania z wykorzystaniem %
imie = 'Ala'
co = 'Kota'
wiadomosc = '%s  ma %s' % (imie, co)
wiadomosc

"""### Wbudowane funkcje

* [help](https://docs.python.org/3/library/functions.html#help)
* [print](https://docs.python.org/3/library/functions.html#print)
* [input](https://docs.python.org/3/library/functions.html#input)
* [len](https://docs.python.org/3/library/functions.html#len)
* [type](https://docs.python.org/3/library/functions.html#type)
* [dir](https://docs.python.org/3/library/functions.html#dir)
"""

help(print)

print('hello from python')
print("hello from print")

tekst = input('Podaj jakiś łańcuch znakowy: ')

print(tekst, len(tekst))

"""## Zadania

### Kolekcje danych

#### Zadanie 1
Utwórz listę zawierającą liczby całkowite, sprawdź jej rozmiar przy użyciu funkcji `len`.
"""

lista = [1, 2, 3, 4, 22, 11]
len(lista)

"""#### Zadanie 2
Zapisz listę do nowej zmiennej, następnie dodaj kolejną liczbę całkowitą korzystając z methody `append`, sprawdź zawartość obu list.
"""

lista_dwa=lista[:]
lista_dwa.append(44)
print(lista+lista_dwa)

"""#### Zadanie 3
Wykonaj operację dodawania na dwóch dowolnych listach zawierających liczby, a następnie zsumuj ([sum](https://docs.python.org/3/library/functions.html#sum)) wynik operacji dodawania i wyświetl go na ekranie.
"""

li3 = lista + lista_dwa
sum(li3)

"""#### Zadanie 4
Utwórz dwa zbiory liczbowe a następnie wykonaj następujące działania na nich: 


*   & (and)
*   | (or)
*   ^ (xor)

Zapisz wyniki do nowych zmiennych, oraz wyświetl je (zmienne) na ekranie.
 


"""

set1 = {1, 7, 11, 13, 17, 19, 23}
set2 = {2, 4, 6, 8, 11, 13, 15, 17, 19, 21}

set3 = set1&set2
print(set3)

set4 = set1|set2
print(set4)

set5 = set1^set2
print(set5)

"""#### Zadanie 5
Wykonaj operację dodawania dwóch zbiorów (**?**). 

Czy da się taką operację wykonać? Jeżeli nie, to czy można coś z tym zrobić?




"""

set5 = set3.union(set1)
print(set5)

"""#### Zadanie 6
Utwórz słownik o nazwie koszyk w którym kluczami będą nazwy owoców a wartościami dowolna liczba całkowita. Wyświetl na ekranie wartość dla dowolnie wybranego przez Ciebie klucza.

"""

koszyk = {'papaja':5,
          'kiwi':3,
          'liczi':4,
          'smoczy_owoc':1}
koszyk['papaja']

"""#### Zadanie 7
Korzystając z operatora przynależności `in`, sprawdź czy w poniższej liście znajduje się wartość `'kot'` oraz `3`. Wypisz wynik na ekranie.
```python
li = [3,4,'pies', 1,2]
``` 

"""

li = [3,4,'pies', 1,2]
'1' in li
1 in li

"""### Struktury kontrolne

#### Zadanie 1
Napisz kod który pobierze od użytkownika imię, jeżeli `imie == 'Azor'` to przywitaj go `'Dobry piesek!'`.

Przykład 1:
```shell
Podaj imię > Michal
Witaj Michal!
```

Przykład 2:
```shell
Podaj imię > Azor
Dobry piesek!
```
"""

imie = input('Jak się wabi? ')

if imie == 'Azor':
  print("Dobry piesek!")

else:
  print('Witaj', imie+"!")

"""#### Zadanie 2
Napisz prosty kalkulator, użytkownik powinien móc wprowadzić liczby zmiennoprzecinkowe (`float`).

przykład:
```shell
Podaj pierwszą liczbę > 1.5
Podaj drugą liczbę > 3.5
Podaj operację (+,-,*,/) > -
wynik: -2.0
```
"""

print('Kalkulator obsługuje tylko podstawowe operacje "+,-,*,/"!')
zmienna1 = float(input('Twoja pierwsza liczba: '))
zmienna2 = float(input('Twoja druga liczba: '))
operacja = input('Wybierz operację: ')

if operacja == '+':
  print(round((zmienna1+zmienna2),2))
elif operacja == '-':
  print(round((zmienna1-zmienna2),2))
elif operacja == '*':
  print(round((zmienna1*zmienna2),2))
elif operacja == '/':
  print(round((zmienna1/zmienna2),2))
else:
  print("Kalkulator nie obsługuje podanej operacji!")

"""#### Zadanie 3
Korzystając z operatora przynależności `in` sprawdź czy podana wartość przez użytkownika znajduje się w liście (z dowolnymi wartościami wybranymi przez Ciebie). Jeżeli wartość znajduje się na liście wyświetl jakiś tekst użytkownikowi.

"""

Mieso = ['żaba', 'konina', 'pszczoła', 'krowa']
print('Witam, czego sobie Pan życzy?')
odp1 = input('"ej... powinieneś coś odpowiedzieć" ')

odp2 = input('Czego Pan potrzebuje? ')



if odp2 in Mieso:
  print("Mamy to w naszym asortymencie, zaraz Panu przyniosę.")
else:
  print('Bardzo mi przykro, wszystkie sztuki zostały wyprzedane.')

"""#### Zadanie 4
Przeiteruj po zbiorze liczb, oraz dodaj sprawdzenie czy aktualna liczba spełnia któryś z warunków:

*  większa
*  mniejsza
*  równa 0

Wyświetl informację użytkownikowi jaki warunek został spełniony.
"""

list = [1, -234, 13, -432, 0, 32, 2]

for x in list:
  if x > 0:
    print(x, 'Jest większe od 0')
  elif x < 0:
    print(x, 'Liczba jest mniejsza od 0')
  elif x == 0:
    print(x, 'Liczba jest równa 0')

"""#### Zadanie 5
Przeiteruj po słowniku `koszyk` utworzonym wcześniej, i wyświetl na ekranie nazwę oraz ilość danego owoca w koszyku.

Na przykład:
```
Banan : 3
Jabłka : 2
```

"""

for papanamija, koszyk_ale_lepszy in koszyk.items():
  print(f"W koszyku jest: {papanamija}; w koszyku znajduje się {koszyk_ale_lepszy} szt.")

"""#### Zadanie 6
Pobierz od użytkownika 5 wartości i umieść je w zbiorze (set.add). Wyświetl zbiór na ekranie.

"""

set11=set()
for x1 in range(5):
  set11.add((float(input(f'Wprowadź kolejną liczbę pętli: '))))
set12=set11
print("Sorted one:", (sorted(set12)))